export default class RouterPaths {
  static readonly About = "About";
  static readonly Login = "Login";
  static readonly ShareHistoryView = "ShareHistoryView";
  static readonly TreeView = "TreeView";
  static readonly CoinsView = "CoinsView";
  static readonly Register = "Register";
  static readonly ArticleView = "ArticleView";
  static readonly ReadHistory = "ReadHistory";
  static readonly Settings = "Settings";
  static readonly CollectHistory = "CollectHistory";
  static readonly CoinsHistoryView = "CoinsHistoryView";
  static readonly SearchView = "SearchView";
}