export default class RouterPaths {
  static readonly AboutView = "AboutView";
  static readonly LoginView = "LoginView";
  static readonly ShareHistoryView = "ShareHistoryView";
  static readonly TreeView = "TreeView";
  static readonly CoinsView = "CoinsView";
  static readonly RegisterView = "RegisterView";
  static readonly ArticleView = "ArticleView";
  static readonly ReadHistory = "ReadHistory";
  static readonly Settings = "Settings";
  static readonly CollectHistoryView = "CollectHistoryView";
  static readonly CoinsHistoryView = "CoinsHistoryView";
  static readonly SearchView = "SearchView";
}